[phases.setup]
nixPkgs = ["python39", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput --settings=config.settings.production",
  "python manage.py migrate --settings=config.settings.production"
]

[start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --settings=config.settings.production"